export const SELECT_DATE = "SELECT_DATE";
export const SELECT_SIZE = "SELECT_SIZE";
export const SET_FRAME_DETAILS = "SET_FRAME_DETAILS";
export const SET_PRICE = "GET_PRICE_WITH_SIZE";
export const SET_DELIVERY = 'SET_DELIVERY';
export const SET_FRAME_COLOR = 'SET_FRAME_COLOR';
// form validation
export const STREET_VALIDATION = 'STREET_VALIDATION';
export const NUMBER_VALIDATION = 'NUMBER_VALIDATION';
export const CITY_VALIDATION = 'CITY_VALIDATION';
export const CODE_VALIDATION = 'CODE_VALIDATION';
export const EMAIL_VALIDATION = 'EMAIL_VALIDATION';
export const EXTRA_MESSAGE_VALIDATION = 'EXTRA_MESSAGE_VALIDATION';
export const NAME_VALIDATION = 'NAME_VALIDATION';
export const PHONE_VALIDATION = 'PHONE_VALIDATION';
export const REGULATION_VALIDATION = 'REGULATION_VALIDATION';
// Basket
export const SHOW_BASKET = 'SHOW_BASKET';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
// Shop
export const SET_SHOP_SECTION = 'SET_SHOP_SECTION';
export const SET_CLIENT_NAME_TO_PRODUCT = 'SET_CLIENT_NAME_TO_PRODUCT';
// Database
export const GET_BIRTHDAY_DATA = 'GET_BIRTHDAY_DATA';
export const GET_BIRTH_DATA = 'GET_BIRTH_DATA';
